<?php

namespace ContainerPj81UyS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAccountControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\AccountController' shared autowired service.
     *
     * @return \App\Controller\AccountController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/AccountController.php';
        include_once \dirname(__DIR__, 4).'/src/Service/Crypto/EnvelopeEncryptionService.php';

        $container->services['App\\Controller\\AccountController'] = $instance = new \App\Controller\AccountController(($container->privates['App\\Service\\OpenBankingService'] ?? $container->load('getOpenBankingServiceService')), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['App\\Repository\\TransactionRepository'] ?? $container->load('getTransactionRepositoryService')), ($container->privates['App\\Service\\Crypto\\EnvelopeEncryptionService'] ??= new \App\Service\Crypto\EnvelopeEncryptionService()));

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Controller\\AccountController', $container));

        return $instance;
    }
}
