<?php

namespace ContainerPj81UyS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCardControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\CardController' shared autowired service.
     *
     * @return \App\Controller\CardController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/CardController.php';
        include_once \dirname(__DIR__, 4).'/src/Service/CardService.php';

        $a = ($container->privates['App\\Service\\CardIssuing\\StripeCardIssuer'] ?? $container->load('getStripeCardIssuerService'));
        $b = ($container->privates['App\\Repository\\CardRepository'] ?? $container->load('getCardRepositoryService'));

        $container->services['App\\Controller\\CardController'] = $instance = new \App\Controller\CardController(new \App\Service\CardService($a, ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), $b, ($container->privates['logger'] ?? self::getLoggerService($container))), $b, $a);

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Controller\\CardController', $container));

        return $instance;
    }
}
