<?php

namespace ContainerPj81UyS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGdprControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\GdprController' shared autowired service.
     *
     * @return \App\Controller\GdprController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/GdprController.php';

        $container->services['App\\Controller\\GdprController'] = $instance = new \App\Controller\GdprController(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['App\\Repository\\CardRepository'] ?? $container->load('getCardRepositoryService')), ($container->privates['App\\Repository\\HceTokenRepository'] ?? $container->load('getHceTokenRepositoryService')), ($container->privates['App\\Repository\\TransactionRepository'] ?? $container->load('getTransactionRepositoryService')), ($container->privates['App\\Service\\HceProvisioningService'] ?? $container->load('getHceProvisioningServiceService')), ($container->privates['logger'] ?? self::getLoggerService($container)));

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Controller\\GdprController', $container));

        return $instance;
    }
}
