<?php

namespace ContainerPj81UyS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHceProvisioningServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\HceProvisioningService' shared autowired service.
     *
     * @return \App\Service\HceProvisioningService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/HceProvisioningService.php';
        include_once \dirname(__DIR__, 4).'/src/Service/CardEncryptionService.php';

        return $container->privates['App\\Service\\HceProvisioningService'] = new \App\Service\HceProvisioningService(($container->privates['App\\Service\\CardIssuing\\StripeCardIssuer'] ?? $container->load('getStripeCardIssuerService')), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['App\\Repository\\HceTokenRepository'] ?? $container->load('getHceTokenRepositoryService')), new \App\Service\CardEncryptionService($container->getEnv('CARD_ENCRYPTION_KEY')), ($container->privates['logger'] ?? self::getLoggerService($container)), $container->getEnv('int:HCE_SESSION_KEY_TTL'));
    }
}
