<?php

namespace ContainerPj81UyS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStripeCardIssuerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\CardIssuing\StripeCardIssuer' shared autowired service.
     *
     * @return \App\Service\CardIssuing\StripeCardIssuer
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/CardIssuing/CardIssuerInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Service/CardIssuing/StripeCardIssuer.php';

        return $container->privates['App\\Service\\CardIssuing\\StripeCardIssuer'] = new \App\Service\CardIssuing\StripeCardIssuer(($container->privates['http_client.uri_template'] ?? $container->load('getHttpClient_UriTemplateService')), $container->getEnv('STRIPE_ISSUING_SECRET_KEY'), 'https://api.stripe.com/v1', ($container->privates['logger'] ?? self::getLoggerService($container)));
    }
}
