<?php

namespace ContainerOoMceCb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDigitalEuroControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\DigitalEuroController' shared autowired service.
     *
     * @return \App\Controller\DigitalEuroController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/DigitalEuroController.php';
        include_once \dirname(__DIR__, 4).'/src/Service/DigitalEuro/DigitalEuroInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Service/DigitalEuro/DigitalEuroStub.php';

        $container->services['App\\Controller\\DigitalEuroController'] = $instance = new \App\Controller\DigitalEuroController(new \App\Service\DigitalEuro\DigitalEuroStub(($container->privates['logger'] ?? self::getLoggerService($container))));

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Controller\\DigitalEuroController', $container));

        return $instance;
    }
}
