<?php

namespace ContainerOoMceCb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHceControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\HceController' shared autowired service.
     *
     * @return \App\Controller\HceController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/HceController.php';

        $container->services['App\\Controller\\HceController'] = $instance = new \App\Controller\HceController(($container->privates['App\\Service\\HceProvisioningService'] ?? $container->load('getHceProvisioningServiceService')), ($container->privates['App\\Repository\\CardRepository'] ?? $container->load('getCardRepositoryService')), ($container->privates['App\\Repository\\HceTokenRepository'] ?? $container->load('getHceTokenRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Controller\\HceController', $container));

        return $instance;
    }
}
