<?php

namespace ContainerOoMceCb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOpenBankingServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\OpenBankingService' shared autowired service.
     *
     * @return \App\Service\OpenBankingService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/OpenBankingService.php';

        return $container->privates['App\\Service\\OpenBankingService'] = new \App\Service\OpenBankingService(($container->privates['http_client.uri_template'] ?? $container->load('getHttpClient_UriTemplateService')), ($container->privates['logger'] ?? self::getLoggerService($container)), $container->getEnv('PSD2_CLIENT_ID'), $container->getEnv('PSD2_CLIENT_SECRET'), $container->getEnv('PSD2_CERT_PATH'), $container->getEnv('PSD2_KEY_PATH'), $container->getEnv('PSD2_API_BASE_URL'), $container->getEnv('APP_CALLBACK_URL'));
    }
}
