<?php

namespace ContainerOoMceCb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getP2PControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\P2PController' shared autowired service.
     *
     * @return \App\Controller\P2PController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/P2PController.php';
        include_once \dirname(__DIR__, 4).'/src/Service/P2PTransferService.php';
        include_once \dirname(__DIR__, 4).'/src/Service/Crypto/BlindIndexService.php';
        include_once \dirname(__DIR__, 4).'/src/Service/Crypto/EnvelopeEncryptionService.php';

        $container->services['App\\Controller\\P2PController'] = $instance = new \App\Controller\P2PController(new \App\Service\P2PTransferService(($container->privates['App\\Service\\OpenBankingService'] ?? $container->load('getOpenBankingServiceService')), ($container->privates['App\\Service\\Crypto\\EnvelopeEncryptionService'] ??= new \App\Service\Crypto\EnvelopeEncryptionService()), new \App\Service\Crypto\BlindIndexService($container->getEnv('BLIND_INDEX_KEY')), ($container->privates['App\\Repository\\UserRepository'] ?? $container->load('getUserRepositoryService')), ($container->privates['App\\Repository\\P2PTransferRepository'] ?? $container->load('getP2PTransferRepositoryService')), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['logger'] ?? self::getLoggerService($container))));

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Controller\\P2PController', $container));

        return $instance;
    }
}
