<?php

namespace ContainerOoMceCb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTopUpControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\TopUpController' shared autowired service.
     *
     * @return \App\Controller\TopUpController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/TopUpController.php';
        include_once \dirname(__DIR__, 4).'/src/Service/TopUpService.php';
        include_once \dirname(__DIR__, 4).'/src/Service/Crypto/EnvelopeEncryptionService.php';

        $container->services['App\\Controller\\TopUpController'] = $instance = new \App\Controller\TopUpController(new \App\Service\TopUpService(($container->privates['App\\Service\\OpenBankingService'] ?? $container->load('getOpenBankingServiceService')), ($container->privates['App\\Service\\Crypto\\EnvelopeEncryptionService'] ??= new \App\Service\Crypto\EnvelopeEncryptionService()), ($container->privates['App\\Repository\\TopUpRepository'] ?? $container->load('getTopUpRepositoryService')), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['logger'] ?? self::getLoggerService($container)), $container->getEnv('EUPAY_CREDITOR_IBAN'), $container->getEnv('EUPAY_CREDITOR_NAME')));

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Controller\\TopUpController', $container));

        return $instance;
    }
}
