<?php

namespace ContainerOoMceCb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getWebAuthnControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\WebAuthnController' shared autowired service.
     *
     * @return \App\Controller\WebAuthnController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/WebAuthnController.php';
        include_once \dirname(__DIR__, 4).'/src/Service/WebAuthn/WebAuthnService.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        $container->services['App\\Controller\\WebAuthnController'] = $instance = new \App\Controller\WebAuthnController(new \App\Service\WebAuthn\WebAuthnService($a, ($container->privates['App\\Repository\\WebAuthnCredentialRepository'] ?? $container->load('getWebAuthnCredentialRepositoryService')), ($container->privates['webauthn.challenge.cache'] ?? $container->load('getWebauthn_Challenge_CacheService')), $container->getEnv('WEBAUTHN_RP_ID'), $container->getEnv('WEBAUTHN_RP_NAME')), $a, ($container->services['lexik_jwt_authentication.jwt_manager'] ?? $container->load('getLexikJwtAuthentication_JwtManagerService')), ($container->privates['logger'] ?? self::getLoggerService($container)));

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Controller\\WebAuthnController', $container));

        return $instance;
    }
}
