<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOoMceCb\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOoMceCb/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOoMceCb.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOoMceCb\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOoMceCb\App_KernelDevDebugContainer([
    'container.build_hash' => 'OoMceCb',
    'container.build_id' => '97ee613b',
    'container.build_time' => 1770761250,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOoMceCb');
