<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPj81UyS\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPj81UyS/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPj81UyS.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPj81UyS\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPj81UyS\App_KernelDevDebugContainer([
    'container.build_hash' => 'Pj81UyS',
    'container.build_id' => '3e479ce3',
    'container.build_time' => 1770756985,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPj81UyS');
